/**
 * This file is generated by hand in order to bootstrap compiler development. It is intended to be an exact match to
 * compiled output.
 */
export declare const _capnpFileId = "e37ded525a68a7c9";
